services:
  - type: web
    name: qa-system-gemini
    env: python
    buildCommand: ./build.sh
    startCommand: bash ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONPATH
        value: /app
      - key: GOOGLE_API_KEY
        sync: false
        # Note: You MUST set this value in the Render dashboard!
      - key: ASTRA_DB_TOKEN
        sync: false
        # Note: You MUST set this value in the Render dashboard!
      - key: ASTRA_DB_ENDPOINT
        sync: false
        # Note: You MUST set this value in the Render dashboard!
      - key: ASTRA_DB_COLLECTION
        value: qa_system_vectors
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: qa-system-gemini
      - key: LANGCHAIN_TRACING_V2
        value: "true"
