services:
  - type: web
    name: qa-system-gemini
    env: python
    buildCommand: ./build.sh
    startCommand: bash ./start.sh
    plan: standard
    # Increase memory and CPU allocation
    autoscaling:
      min_instances: 1
      max_instances: 1
    # Increase startup timeout to allow for model loading
    healthCheckPath: /health
    healthCheckTimeout: 300
    # Optimize for memory usage
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONPATH
        value: /app
      - key: DISABLE_VECTOR_DB
        value: "true"
      - key: DISABLE_SENTENCE_TRANSFORMER
        value: "true"
      - key: DISABLE_LANGSMITH
        value: "true"
      - key: LIGHTWEIGHT_MODE
        value: "true"
      - key: LAZY_LOAD_MODELS
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONOPTIMIZE
        value: "1"
      - key: GOOGLE_API_KEY
        sync: false
        # Note: You MUST set this value in the Render dashboard!
      - key: ASTRA_DB_TOKEN
        sync: false
        # Note: You MUST set this value in the Render dashboard!
      - key: ASTRA_DB_ENDPOINT
        sync: false
        # Note: You MUST set this value in the Render dashboard!
      - key: ASTRA_DB_COLLECTION
        value: qa_system_vectors
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: qa-system-gemini
      - key: LANGCHAIN_TRACING_V2
        value: "true"
